name: Github-Hosts

on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth:   # 明确获取完整历史

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run jar Create hosts
        run: java -jar target/github-hosts-1.1.jar

      - name: Clear target
        run: rm -rf target/

      - name: Commit changes
        id: commit
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions [Bot]"
          
          # 强制重置到远程最新状态（丢弃任何并发修改）
          git fetch origin
          git reset --hard origin/master
          
          # 重新生成文件后提交
          git add .
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git commit -m "update hosts and readme [skip ci]"
          fi

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true  # 强制推送以覆盖远程（适用于自动生成的文件）
